# Generated by Django 3.2.7 on 2025-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('R', 'Red'), ('Y', 'Yellow'), ('G', 'Green')], default='R', max_length=1)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
